### ISSUE TITLE
An Amazing Add-On

### ISSUE THREAD

**Issue by Tyson3101** [SoRadGaming/Auto-Youtube-Shorts-Scroller#3]
Hi, I just found this and thought it was cool that you made my extension work on firefox. (Sorry you had to go through the mess of my code lol)
I also wanted to let you know I added this to my [ReadMe](https://github.com/Tyson3101/Auto-Youtube-Shorts-Scroller#readme) so it can help people find this better.

**Comment by SoRadGaming** [comment]
Appreciate the kind words, and thank you so much for creating this extension in the first place. Great for my second vertical monitor while working.
